server:
  port: 8081
  tomcat:
    max-swallow-size: 100MB         # to catch file size exceed exception in spring.

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
